### ISSUE TITLE
Search in output

### ISSUE THREAD

**Issue by friuns2** [thorgeirk11/REX-Diagnostics#18]
![image](https://user-images.githubusercontent.com/16543239/34918770-fc7d8440-f960-11e7-8ee1-6cccb0ca3f2a.png)

i think would be usefull to filter fields in output

**Comment by thorgeirk11** [comment]
Fantastic Idea!

How would like to see that implemented?
I can think of a few aproches:
1. Simple toggle to fliter out just Private/public fields
2. Text field to filter based on name of the fields
3. Just show the imidiate fields and not inheriated onces

Also maybe remember the filter setting on the same type of object 🤔 

All comments wellcome! 🎉

**Comment by friuns2** [comment]
i was thinking about 2. approach like project window has https://i.imgur.com/I6S4Lb8.png

**Comment by thorgeirk11** [comment]
Alright @friuns2 can you take this change for a spin and tell me your thoughts? 👍

**Comment by friuns2** [comment]
yes works very well thanks! waiting for multiline ;)

**Comment by thorgeirk11** [comment]
Fantastic I am going to close this issue then, thanks for the suggestion 

The multiline is quite tricky because of how I do the code completion 🤔 but I will try to make it work 👍
