### ISSUE TITLE
new unity ui seems broke a bit rex

### ISSUE THREAD

**Issue by friuns2** [thorgeirk11/REX-Diagnostics#25]
![image](https://user-images.githubusercontent.com/16543239/73785988-15d7ea80-47a1-11ea-9a2f-1fb2178515bf.png)

**Comment by SugoiDev** [comment]
Changing [this line](https://github.com/thorgeirk11/REX-Diagnostics/blob/b18a1f0ec7c4e93b6449ebaff2cf2f28a0fd8712/RexWindowProject/Assets/RexDiagnostics/Editor/UI/RexEditorWindow.cs#L467)

```
var rect = new Rect(1, i * lineHeigth, intelliRect.width, intelliRect.height);
```

To this:

```
var rect = new Rect(1, i * lineHeigth, intelliRect.width, lineHeigth);
```

Might solve that.

I use a heavily modified ReX, but I think I fixed that issue a while ago with that change.

**Comment by friuns2** [comment]
Thanks it worked!

**Comment by thorgeirk11** [comment]
@SugoiDev I would love to get a PR :D 
I have not had any time to work on this extension ☹️

**Comment by SugoiDev** [comment]
@thorgeirk11 Oh, of course! I'll submit one for this change later today.

(Thanks for all your work. REX is pretty cool and useful!)
