### ISSUE TITLE
Cursor maintains position when hitting Enter

### ISSUE THREAD

**Issue by Skybladev2** [thorgeirk11/REX-Diagnostics#7]
Instead of going to the end of line cursor stays where it was when user hits Enter.
This slows down typing speed.

**Comment by thorgeirk11** [comment]
Hi @Skybladev2 and thanks for your interest!

I am quite sure that this has been fixed since I published V1.1. You can pull directly from master to get the latest, master branch *should* be a stable version of the tool.

**Comment by Skybladev2** [comment]
Ah, ok. I just installed the plugin from the asset store and did not check if source code is newer.

**Comment by thorgeirk11** [comment]
Woops, So yeah I plan on pushing out a update on next Sunday to the asset store. Unity always takes some time to go over the update so I hope it will be available next week
